version: "3.8"

services:
  fastapi_app:
    build: baqdauled/whatsapp_confirmation
    container_name: fastapi_app
    ports:
      - "8001:8000"
    environment:
      TZ: "UTC"
    env_file:
      - .env
    restart: unless-stopped
