name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main
  workflow_dispatch: # Возможность вручную запустить workflow

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest .

      # Пуш Docker-образа
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      # Подключение к серверу и обновление контейнера
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }} # Или используйте secrets.SERVER_SSH_KEY для ключа
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/${{ secrets.DOCKER_IMAGE_NAME }}
            git pull
            docker compose pull # Загружаем новую версию образа
            docker compose up -d # Перезапускаем контейнеры с новой версией
            docker system prune